/**
 * EDGE PANEL — Capability Manifest.
 *
 * Every entry here corresponds to a feature that is actually implemented in
 * this codebase (proxy, protocol, config builder, store, API, UI, CI, docs).
 * Nothing is aspirational or advertising. The UI shows the total count and
 * lets admins filter/read the list.
 */
import { GAME_CATALOG } from './games';

export type CapabilityCategory =
  | 'protocol'
  | 'traffic'
  | 'config'
  | 'sub'
  | 'scanner'
  | 'security'
  | 'owner'
  | 'ui'
  | 'deploy'
  | 'settings';

export interface Capability {
  id: string;
  category: CapabilityCategory;
  title: string;
  description: string;
}

const c = (
  category: CapabilityCategory,
  id: string,
  title: string,
  description: string,
): Capability => ({ id, category, title, description });

export const CAPABILITIES: Capability[] = [
  // ----------------------------------------------------------------- protocol
  c('protocol', 'proto-vless', 'پروتکل VLESS', 'پیادهسازی کامل هدر VLESS: نسخه، UUID، Addon، Command، Port و آدرس مقصد.'),
  c('protocol', 'proto-ws', 'حملونقل WebSocket', 'پروکسی VLESS روی WebSocket با مدیریت پیامهای دودویی.'),
  c('protocol', 'proto-tls', 'TLS روی Cloudflare', 'اتصال به مقصد فقط از طریق پورتهای TLS مجاز کلودفلر (443 و پورتهای اختصاصی).'),
  c('protocol', 'proto-ed', 'Early Data', 'پشتیبانی از Early Data clients؛ اولین پیام WS میتواند هدر و داده را با هم داشته باشد.'),
  c('protocol', 'proto-ed4096', 'Early Data تا ۴۰۹۶', 'در پروفایل GOD حداکثر Early Data 4096 بایت در کانفیگ صادر میشود.'),
  c('protocol', 'proto-tcp', 'پروکسی TCP', 'پایپینگ دوطرفه داده بین کلاینت و مقصد TCP.'),
  c('protocol', 'proto-udp-dns', 'UDP فقط برای DNS', 'فرمان UDP فقط با پورت 53 پذیرفته میشود؛ بقیهٔ UDP رد میشود (جلوگیری از Open Proxy).'),
  c('protocol', 'proto-doh-relay', 'DNS از طریق DoH', 'کوئری DNS کلاینت بهصورت RFC 8484 به DNS-over-HTTPS ارسال و پاسخ دوباره به کلاینت برگردانده میشود.'),
  c('protocol', 'proto-doh-failover', 'Failover حلکنندههای DoH', 'در شکست سرویسدهندهٔ اصلی، به ترتیب از DoHهای جایگزین استفاده میشود.'),
  c('protocol', 'proto-dns-alts', 'چند Resolver جایگزین', 'لیست قابل تنظیم DoH جایگزین در تنظیمات پنل.'),
  c('protocol', 'proto-mux-reject', 'جلوگیری از MUX', 'فرمان 0x03 (MUX) صریحاً رد میشود تا رفتار پروکسی قابل پیشبینی بماند.'),
  c('protocol', 'proto-stream-safe', 'پارسر امن جریان', 'پارسر هدر VLESS برای جریانهای ناقص و چندبخشی طراحی شده (need-more).'),
  c('protocol', 'proto-ipv4', 'آدرس IPv4 مقصد', 'پشتیبانی از چارچوب IPv4 در هدر VLESS.'),
  c('protocol', 'proto-ipv6', 'آدرس IPv6 مقصد', 'پشتیبانی از چارچوب IPv6 در هدر VLESS.'),
  c('protocol', 'proto-domain', 'آدرس دامنه مقصد', 'پشتیبانی از نام دامنه با طول تا ۲۵۵ بایت در هدر VLESS.'),
  c('protocol', 'proto-tcp-retry', 'TCP connect retry', 'درخواست اتصال TCP بر اساس preset با retry اجرا میشود.'),
  c('protocol', 'proto-tls-sni', 'SNI واقعی', 'SNI و Host فقط از دامنهٔ واقعی که کلاینت به Worker متصل شده ساخته میشود؛ بدون SNI جعلی و بدون دامنهٔ ثالث.'),
  c('protocol', 'proto-no-smtp', 'مسدودسازی پورتهای SMTP', 'پورتهای 25، 465، 587 و 2525 همیشه رد میشوند.'),
  c('protocol', 'proto-no-private', 'مسدودسازی IP خصوصی (Literal)', 'آدرسهای IP میزبان (از جمله Literal) در بازههای خصوصی/رزروشده قبل از اتصال رد میشوند.'),
  c('protocol', 'proto-no-meta', 'مسدودسازی Metadata', 'آدرسهای خصوصی حاصل از رزولوشن دامنه (مثل 169.254.169.254) قبل از اتصال رد میشوند.'),
  c('protocol', 'proto-udp-framing', 'قاببندی پاسخ UDP', 'پاسخ UDP/DNS با پیشوند ۲ بایتی طول طبق پروتکل VLESS ارسال میشود.'),
  c('protocol', 'proto-conn-cap', 'سقف اتصال همزمان', 'سقف مستقل اتصالات WebSocket برای هر مشترک در Backend اعمال میشود.'),
  c('protocol', 'proto-ip-literal-parse', 'تشخیص IPهای یکتا', 'تشخیص صحیح آدرسهای IPv4 و IPv6 literal و IPv4-mapped برای مسدودسازی.'),
  c('protocol', 'proto-path-binding', 'مسیرهای اختصاصی هر مشترک', 'هر مشترک مسیرهای URL منحصربهفرد دارد و فقط با آنها قابل اتصال است.'),
  c('protocol', 'proto-uuid-auth', 'احراز با UUID واگذارشده', 'اتصال WS فقط با UUID فعال عضو پذیرفته میشود.'),
  c('protocol', 'proto-active-check', 'بررسی فعال بودن مشترک در اتصال', 'مشترک غیرفعال نمیتواند WebSocket برقرار کند.'),
  c('protocol', 'proto-expiry-check', 'بررسی انقضای اشتراک', 'پس از اتمام زمان، اتصالهای جدید رد میشوند.'),
  c('protocol', 'proto-tls-port-check', 'بررسی پورت TLS مجاز', 'پورت مقصد باید در فهرست پورتهای TLS مجاز کلودفلر باشد.'),
  c('protocol', 'proto-ws-ping', 'کنترل دسترسی WebSocket', 'پذیرش یا رد دسترسی در مرحلهٔ WebSocket بهدور از رقابت انجام میشود (آگاهی از سقف همزمان).'),
  c('protocol', 'proto-close-ws', 'بستن تمیز اتصال', 'بستن صحیح WebSocket در پایان جریان و آزاد کردن شمارندهٔ نشستها.'),
  c('protocol', 'proto-host-validation', 'اعتبارسنجی Host اتصال', 'Host هدر کلاینت با مسیر مشترک هماهنگ است؛ دامنهها فقط دامنههای همین Worker.'),
  // --------------------------------------------------------------- traffic
  c('traffic', 'tr-usage', 'شمارش تقریبی مصرف', 'ترافیک هر مشترک بهصورت تقریبی (بالا/پایین) شمارش و در DO ذخیره میشود.'),
  c('traffic', 'tr-session-count', 'شمارش نشستها', 'تعداد نشستهای WebSocket فعال هر مشترک در لحظه محاسبه میشود.'),
  c('traffic', 'tr-cap-bytes', 'سقف حجم', 'اعمال محدودیت حجم؛ مازاد بر سقف، اتصال جدید بسته میشود.'),
  c('traffic', 'tr-remaining', 'نمایش حجم باقیمانده', 'محاسبه و نمایش حجم باقیمانده در پنل و منوی مشترک.'),
  c('traffic', 'tr-reset-usage', 'ریست مصرف', 'یککلیکه صفر شدن حجم مصرفی مشترک (Audit ثبت میشود).'),
  c('traffic', 'tr-reset-conn', 'ریست اتصال', 'صفر شدن شمارندهٔ اتصال/نشست مشترک.'),
  c('traffic', 'tr-last-seen', 'آخرین اتصال', 'ثبت و نمایش زمان آخرین اتصال هر مشترک.'),
  c('traffic', 'tr-unlimited-bytes', 'حجم نامحدود', 'مقدار صفر در Backend مساوی حجم نامحدود است و به مقدار پیشفرض تبدیل نمیشود.'),
  c('traffic', 'tr-unlimited-time', 'زمان نامحدود', 'صفر = بدون انقضا؛ هیچ تبدیل خودکار به مقدار پیشفرض وجود ندارد.'),
  c('traffic', 'tr-unlimited-conn', 'اتصال نامحدود', 'صفر = بدون سقف نشستن؛ در UI با دکمهٔ ∞ انتخاب میشود.'),
  c('traffic', 'tr-limit-bytes', 'محدودیت حجم گیگابایت', 'محدوده حجم بر حسب بایت از فرم گیگابایت در UI.'),
  c('traffic', 'tr-limit-time', 'محدودیت زمان', 'محدودهٔ زمانی بر حسب روز در فرم و تبدیل به تامپ استامپ.'),
  c('traffic', 'tr-traffic-stats', 'آمار کلی مصرف', 'مصرف کل ترافیک در داشبورد.'),
  c('traffic', 'tr-active-users', 'شمارش کاربران فعال', 'آمار کاربران فعال/غیرفعال در داشبورد.'),
  // ---------------------------------------------------------------- config
  c('config', 'cfg-2xx', 'بازسازی تا ۲۰۰۰ مسیر', 'هر اشتراک بر اساس سطح قدرت می‌تواند ۱ تا ۲۰۰۰ مسیر داشته باشد.'),
  c('config', 'cfg-2-path', 'انتخاب تعداد مسیر', 'تعداد مسیر قابل انتخاب از ۱ تا سقف قدرت ۵، ۱۰۰، ۵۰۰ یا ۲۰۰۰ در سازنده و ساخت اتومات است.'),
  c('config', 'cfg-endpoints', 'تنوع کنترلشدهٔ Endpoint', 'فقط از Endpointهای تعریفشده در تنظیمات (حداکثر ۵۰) برای مسیرها استفاده میشود.'),
  c('config', 'cfg-ports', 'پورتهای TLS مجاز کلودفلر', 'انتخاب پورت از فهرست پورتهای TLS کلودفلر (پیشفرض ۴۴۳ برای workers.dev).'),
  c('config', 'cfg-fp', 'Fingerprint مرورگرها', 'پشتیبانی از Chrome، Firefox، Safari، Edge و Random در کانفیگهای خروجی.'),
  c('config', 'cfg-template', 'قالب نام کانفیگ', 'قالب عمومی نام کانفیگ با متغیرهای {brand} {app} {user} {profile} {index} {endpoint} {port}.'),
  c('config', 'cfg-brand', 'برند در نامها', 'برند «AMINCK GOD Edition» در نام پیشفرض کانفیگها و عنوان Subscription لحاظ میشود.'),
  c('config', 'cfg-custom-name', 'نام کانفیگ اختصاصی مشترک', 'هر مشترک میتواند قالب نام اختصاصی داشته باشد.'),
  c('config', 'cfg-v2ray-b64', 'خروجی V2Ray Base64', 'لیست لینکهای VLESS با Encode Base64 برای Import در اپها.'),
  c('config', 'cfg-raw', 'خروجی Raw VLESS URI', 'لینکهای VLESS خام بههمراه fragment نامدار در یک بلوک متنی.'),
  c('config', 'cfg-clash', 'خروجی Clash Meta YAML', 'کانفیگ کامل Clash Meta با پروکسیهای VLESS-WS-TLS.'),
  c('config', 'cfg-singbox', 'خروجی sing-box JSON', 'کانفیگ sing-box با TUN، Mixed، DoH و روتر.'),
  c('config', 'cfg-gauto', 'گروه NOVA-AUTO', 'گروه url-test با health-check و مختصات خودکار در خروجی Clash.'),
  c('config', 'cfg-gfallback', 'گروه NOVA-FALLBACK', 'گروه fallback در خروجی Clash برای تعویض مسیر خراب.'),
  c('config', 'cfg-gbalance', 'گروه NOVA-BALANCE', 'گروه load-balance در خروجی Clash برای پخش بار.'),
  c('config', 'cfg-gsmart', 'گروه NOVA-SMART', 'Selector اصلی که به کاربر اجازهٔ انتخاب بین گروهها و ذخیرهٔ انتخاب میدهد (cache-file در Clash).'),
  c('config', 'cfg-unified-delay', 'unified-delay در Clash', 'فعالسازی unified-delay در خروجی Clash Meta.'),
  c('config', 'cfg-tcp-concurrent', 'tcp-concurrent در Clash', 'فعالسازی tcp-concurrent روی پروکسیها در پروفایلهای Turbo و GOD.'),
  c('config', 'cfg-health-interval', 'Health Check ادواری', 'بازهٔ الفتح پریودیک گروهها در خروجی Clash از پروفایل سرعت.'),
  c('config', 'cfg-tolerance', 'Tolerance قابل تنظیم', 'Tolerance گروه url-test از پروفایل سرعت گرفته میشود.'),
  c('config', 'cfg-health-url', 'Health URL قابل تنظیم', 'آدرس Health Check در خروجی‌ها از تنظیمات پنل؛ خالی یعنی gstatic مستقل تا اتصال به خود Worker باعث Loop نشود.'),
  c('config', 'cfg-sing-urltest', 'URLTest در sing-box', 'خروجی sing-box با اورتست برای انتخاب بهترین مسیر.'),
  c('config', 'cfg-sing-selector', 'Selector در sing-box', 'Selector با قابلیت انتخاب دستی در sing-box.'),
  c('config', 'cfg-sing-tun', 'TUN inbound در sing-box', 'ورودی TUN با auto_route در خروجی sing-box.'),
  c('config', 'cfg-sing-mixed', 'Mixed inbound در sing-box', 'ورودی Mixed (HTTP+SOCKS) در خروجی sing-box.'),
  c('config', 'cfg-sing-doh', 'DoH در sing-box', 'سرورهای DNS-over-HTTPS در خروجی sing-box.'),
  c('config', 'cfg-sing-direct', 'Direct برای شبکه خصوصی', 'قوانین مسیریابی به سمت «direct» برای IPهای خصوصی در sing-box.'),
  c('config', 'cfg-sing-smart', 'مسیریاب نهایی هوشمند', 'Rule نهایی MATCH به سمت Selector هوشمند در sing-box.'),
  c('config', 'cfg-naming-unique', 'نامهای یکتا در خروجی', 'بهکمک متغیر {index} همهٔ نامها در خروجیها یکتا هستند.'),
  c('config', 'cfg-encoded-name', 'پیوندنام در URI', 'نام کانفیگ بهصورت URL-encoded در Fragment لینک VLESS درج میشود.'),
  // ------------------------------------------------------------------- sub
  c('sub', 'sub-link', 'لینک Subscription مستقل', 'هر مشترک یک لینک /sub با Token مستقل دارد.'),
  c('sub', 'sub-token-indep', 'UUID و Token مستقل', 'UUID (برای پراکسی) و Token (برای ساب) دو مقدار کاملاً مستقل هستند.'),
  c('sub', 'sub-userinfo', 'هدر subscription-userinfo', 'خروجی ساببش شامل upload/download/total/expire در هدر است.'),
  c('sub', 'sub-interval', 'فاصلهٔ Update قابل تنظیم', 'هدر profile-update-interval از تنظیمات پنل ساخته میشود.'),
  c('sub', 'sub-support-url', 'هدر support-url', 'لینک پشتیبانی به کلاینتها ارسال میشود.'),
  c('sub', 'sub-v2ray', 'ساببش فرمت V2Ray', 'خروجی ساببش با قالب V2Ray (Base64) برای V2RayNG/MahsaNG/V2Box/NapsternetV.'),
  c('sub', 'sub-clash', 'ساببش فرمت Clash', 'ساببش با ?format=clash برای Clash Meta.'),
  c('sub', 'sub-singbox', 'ساببش فرمت sing-box', 'ساببش با ?format=singbox برای sing-box.'),
  c('sub', 'sub-raw', 'ساببش خام', 'ساببش با ?format=raw برای نمایش مستقیم لینکها.'),
  c('sub', 'sub-multi-route', 'چند مسیر در یک اشتراک', 'یک Subscription میتواند چند مسیر را مدیریت کند.'),
  c('sub', 'sub-last-fetch', 'آخرین دریافت ساببش', 'زمان آخرین درخواست ساببش هر مشترک ثبت میشود.'),
  c('sub', 'sub-user-agent', 'تشخیص کلاینت', 'User-Agent درخواست ساببش در لاگ ثبت میشود (بدون ذخیرهٔ دادههای شخصی).'),
  c('sub', 'sub-disposition', 'فایل ساببش', 'هدر Content-Disposition با نام ساببش بههمراه نوع فایل مناسب.'),
  // -------------------------------------------------------------- scanner
  c('scanner', 'scan-https', 'اسکن HTTPS از Edge', 'اندازه‌گیری زمان رسیدن Header پاسخ HTTPS از Edge کلودفلر با fetch.'),
  c('scanner', 'scan-health-path', 'Probe مسیر Health', 'درخواست Probe به /healthz دامنه Worker فرستاده و نتیجه ذخیره می‌شود.'),
  c('scanner', 'scan-timeout', 'Timeout قابل تنظیم', 'مهلت هر اسکن از پروفایل سرعت گرفته میشود.'),
  c('scanner', 'scan-max50', 'حداکثر ۵۰ Endpoint', 'پنل اسکن حداکثر ۵۰ Endpoint را مدیریت میکند.'),
  c('scanner', 'scan-sort', 'مرتبسازی سالمها', 'لیست Endpointهای سالم با کمترین تأخیر مرتب میشود.'),
  c('scanner', 'scan-save', 'ذخیرهٔ نتایج', 'نتایج پرچکلیتها (latency/status) در تنظیمات ذخیره میشود.'),
  c('scanner', 'scan-auto-before-build', 'Probe خودکار پیش از ساخت', 'ساخت اتومات پیش از تولید ساب Endpointها را از Edge تست می‌کند و به Cron حساب نیاز ندارد.'),
  c('scanner', 'scan-note', 'توضیح صادقانهٔ اندازهگیری', 'در پنل توضیح داده میشود که عدد نشاندادهشده پینگ دستگاه کاربر نیست.'),
  c('scanner', 'scan-probe-now', 'Probe دستی', 'دکمهٔ «Probe اکنون» برای اسکن فوری.'),
  c('scanner', 'scan-add', 'افزودن Endpoint', 'افزودن Endpoint با Host و Port دلخواه (با اعتبارسنجی).'),
  c('scanner', 'scan-remove', 'حذف Endpoint', 'حذف Endpoint از فهرست همراه با نتایجش.'),
  c('scanner', 'scan-auto-build', 'استفادهٔ سریع از بهترین Endpointها', 'ساخت اتومات از نتایج اسکن برای ترتیب مسیرها استفاده میکند.'),
  // ------------------------------------------------------------- security
  c('security', 'sec-random-session', 'Session تصادفی ۲۵۶ بیتی', 'Cookie یک Bearer Token تصادفی ۶۴ رقمی است که فقط با Session فعال داخل Durable Object معتبر می‌شود.'),
  c('security', 'sec-cookie-httponly', 'HttpOnly', 'کوکی نشست با پرچم HttpOnly صادر میشود.'),
  c('security', 'sec-cookie-secure', 'Secure', 'کوکی نشست فقط روی HTTPS ارسال میشود.'),
  c('security', 'sec-cookie-samesite', 'SameSite=Strict', 'کوکی نشست با SameSite=Strict صادر میشود.'),
  c('security', 'sec-session-expiry', 'انقضای نشست', 'نشستها Max-Age دارند و پس از انقضا باطل میشوند.'),
  c('security', 'sec-session-invalidate', 'باطلسازی در یک درخواست', 'نشست ادمین غیرفعالشده در اولین درخواست بعدی باطل میشود.'),
  c('security', 'sec-login-delay', 'Login delay', 'پس از ورود ناموفق، تأخیر اجباری قبل از پاسخ اعمال میشود.'),
  c('security', 'sec-login-rate', 'محدودکردن تلاش ورود', 'پس از چند شکست متوالی، ورود برای مدتی قفل میشود.'),
  c('security', 'sec-sameorigin', 'بررسی Same-Origin', 'درخواستهای تغییردهنده با هدر Origin ناهمخواند رد میشوند (anti-CSRF).'),
  c('security', 'sec-csp', 'CSP', 'Content-Security-Policy با منبع خودی برای اسکریپت و استایل.'),
  c('security', 'sec-xframe', 'X-Frame-Options', 'هدر DENY برای جلوگیری از Frame.'),
  c('security', 'sec-referrer', 'Referrer-Policy', 'ارسال نکردن Referrer به خارج (no-referrer).'),
  c('security', 'sec-permissions', 'Permissions-Policy', 'غیرفعالکردن دوربین، میکروفن و موقعیت در هدر.'),
  c('security', 'sec-nosniff', 'X-Content-Type-Options', 'nosniff برای همهٔ پاسخها.'),
  c('security', 'sec-no-open-proxy', 'جلوگیری از Open Proxy', 'فقط مشترکهای احرازهویتشده و با route مجاز میتوانند پروکسی شوند.'),
  c('security', 'sec-private-block', 'بلاک dest خصوصی برای همه', 'هم TCP و هم UDP، مسیرهای خصوصی/رزروشده رد میشوند.'),
  c('security', 'sec-udp-dns-only', 'UDP فقط ۵۳', 'بستهٔ UDP با پورت غیر ۵۳ رد میشود.'),
  c('security', 'sec-token-random', 'Token تصادفی', 'Token و شناسهها با CSPRNG (crypto.getRandomValues) ساخته میشوند.'),
  c('security', 'sec-secret-not-in-git', 'بدون Secret در Git', '.dev.vars و فایلهای مشابه در .gitignore مسدود شدهاند.'),
  c('security', 'sec-healthz', 'اتصال Health عمومی', 'اندپوینت /healthz بدون احراز و با CORS برای Checkهای بیرونی.'),
  c('security', 'sec-no-3rd-sni', 'بدون SNI شخص ثالث', 'SNI و Host فقط دامنهٔ واقعی Worker است؛ بدون دامنهٔ جعلی.'),
  c('security', 'sec-time-safe', 'مقایسهٔ زمان-ایمن hash', 'مقایسهٔ HMAC و Password Hash بدون وابستگی به زمان اجرا.'),
  // ---------------------------------------------------------------- owner
  c('owner', 'own-login', 'ورود مالک با ADMIN_PASSWORD', 'مالک (AMINCK) فقط با ADMIN_PASSWORD وارد میشود.'),
  c('owner', 'own-username', 'نام کاربری مالک', 'نام کاربری مالک «AMINCK» است و ورود با نام خالی نیز پذیرفته میشود.'),
  c('owner', 'own-all-perm', 'همهٔ Permissionها برای مالک', 'مالک هر ده Permission را به صورت سخت در کد دارد.'),
  c('owner', 'own-no-delete', 'مالک غیرقابل حذف', 'محافظت Backend: حذف/غیرفعالکردن مالک همیشه با خطا رد میشود.'),
  c('owner', 'own-role-fixed', 'نقش مالک ثابت', 'نقش مالک (owner) قابل تغییر نیست.'),
  c('owner', 'own-power-fixed', 'قدرت مالک ثابت', 'سطح قدرت مالک همیشه ultra است و قابل کاهش نیست.'),
  c('owner', 'own-seed', 'پیادهسازی خودکار مالک', 'ریکورد مالک در اولین اجرای Durable Object خودکار ساخته میشود.'),
  c('owner', 'adm-list', 'فهرست ادمینها', 'نمایش همهٔ ادمینها با نقش، اگر فعال، آخرین ورود.'),
  c('owner', 'adm-create', 'ساخت ادمین', 'ایجاد حساب کارمندان با Username/Password مستقل.'),
  c('owner', 'adm-indep-pass', 'رمز مستقل هر ادمین', 'رمز هر ادمین مستقل ذخیره و بررسی میشود.'),
  c('owner', 'adm-pbkdf2', 'PBKDF2-SHA256', 'رمز ادمینها با PBKDF2-SHA256 (۲۱۰هزار دور) قوی ذخیره میشود.'),
  c('owner', 'adm-salt', 'Salt تصادفی ۱۶ بایت', 'برای هر ادمین Salt تصادفی تولید میشود.'),
  c('owner', 'adm-minpass', 'رمز حداقل ۱۰ کاراکتر', 'اعمال min برای ساخت و تغییر رمز ادمینها.'),
  c('owner', 'adm-no-hash-api', 'عدم نمایش hash در API', 'فیلد hash هرگز در پاسخهای API نمیآید.'),
  c('owner', 'adm-no-salt-api', 'عدم نمایش salt در API', 'فیلد salt هرگز در پاسخهای API نمیآید.'),
  c('owner', 'adm-pass-change', 'تعویض رمز ادمین', 'GetAdmin میتواند رمز خود یا دیگران (با مجوز) را تغییر دهد.'),
  c('owner', 'adm-revoke', 'قطع فوری دسترسی', 'با revoke شدن، نشستها فوراً باطل و اتصال ادمین قطع میشود.'),
  c('owner', 'adm-restore', 'وصل مجدد دسترسی', 'ریکر ادمین بدون تغییر رمز قابل بازگرداندن است.'),
  c('owner', 'adm-delete', 'حذف ادمین', 'حذف ادمین همراه با پاککردن همهٔ نشستهایش.'),
  c('owner', 'adm-last-login', 'نمایش آخرین ورود', 'هر ورود موفق، lastLoginAt ادمین را بهروز میکند.'),
  c('owner', 'role-admin', 'نقش admin', 'admins کامل بهجز مدیریت تنظیمات و ادمینها.'),
  c('owner', 'role-operator', 'نقش operator', 'مدیریت کاربران بدون حذف و بدون تنظیمات و ادمینها.'),
  c('owner', 'role-support', 'نقش support', 'فقط مشاهدهٔ کاربران، ساخت کانفیگ و مشاهدهٔ لاگ.'),
  c('owner', 'perm-users-view', 'Permission: users:view', 'دیدن لیست و جزئیات کاربران.'),
  c('owner', 'perm-users-create', 'Permission: users:create', 'ایجا کاربر جدید.'),
  c('owner', 'perm-users-edit', 'Permission: users:edit', 'ویرایش کاربر، ریستها، چرخش کلید.'),
  c('owner', 'perm-users-delete', 'Permission: users:delete', 'حذف کاربر — فقط نقش صاحب admin.'),
  c('owner', 'perm-configs', 'Permission: configs:build', 'ساخت کانفیگ برای هر کاربر.'),
  c('owner', 'perm-settings', 'Permission: settings:manage', 'ویرایش تنظیمات پنل — فقط owner.'),
  c('owner', 'perm-probe', 'Permission: endpoints:probe', 'اجرای Probe و مدیریت Endpointها.'),
  c('owner', 'perm-backup', 'Permission: backup:export', 'دریافت بکومپ JSON کامل.'),
  c('owner', 'perm-admins', 'Permission: admins:manage', 'مدیریت ادمینها — فقط owner.'),
  c('owner', 'perm-audit', 'Permission: audit:view', 'مشاهدهٔ لاگ حوادث.'),
  c('owner', 'power-limited', 'سطح قدرت Limited', 'حداکثر ۵ مسیر برای هر کانفیگ — همیشه در Backend اعمال میشود.'),
  c('owner', 'power-normal', 'سطح قدرت Normal', 'حداکثر ۳۰ مسیر در Backend.'),
  c('owner', 'power-strong', 'سطح قدرت Strong', 'حداکثر ۸۰ مسیر در Backend.'),
  c('owner', 'power-ultra', 'سطح قدرت Ultra', 'حداکثر ۲۰۰۰ مسیر در Backend با هشدار Giant بالاتر از ۲۰۰.'),
  c('owner', 'power-backend', 'قدرت فقط در Backend', 'حتی با درخواست مستقیم API هم محدودیت قدرت اعمال میشود (تستشده).'),
  c('owner', 'power-ui-hint', 'نمایش قدرت در UI', 'قدرت ادمین در پاسخ /api/me و لندینگ API نمایش داده میشود.'),
  c('owner', 'perm-btn-hide', 'مخفی کردن دکمههای بدون مجوز', 'دکمهٔ Hot-Update فقط با settings:manage روی لندینگ دیده میشود.'),
  c('owner', 'perm-api-enforce', 'بررسی Permission در تمام APIها', 'تمام اندپوینتهای API سطح دسترسی را در Backend چک میکنند.'),
  c('owner', 'own-audit-login', 'لاگ ورود مالک/ادمین', 'هر ورود/خروج موفق در لاگ حوادث ثبت میشود.'),
  c('owner', 'own-audit-fail', 'لاگ ورود ناموفق', 'شکستهای ورود با یوزرنیم، IP و زمان ثبت میشوند.'),
  c('owner', 'own-audit-adm-create', 'لاگ ساخت ادمین', 'ساخت ادمین با actor و جزئیات ثبت میشود.'),
  c('owner', 'own-audit-adm-delete', 'لاگ حذف ادمین', 'حذف ادمین در لاگ حوادث ثبت میشود.'),
  c('owner', 'own-audit-revoke', 'لاگ قطع دسترسی', 'عملیات revoke با جزئیات در لاگ ثبت میشود.'),
  c('owner', 'own-audit-restore', 'لاگ وصل مجدد', 'بازگرداندن دسترسی ادمین ثبت میشود.'),
  c('owner', 'own-audit-pass', 'لاگ تغییر رمز', 'تغییر رمز ادمین ثبت میشود (بدون نمایش خود رمز).'),
  c('owner', 'own-audit-actor', 'Actor در لاگها', 'نام کاربری فرد اقدامکننده به همراه هر رویداد نگهداری میشود.'),
  c('owner', 'own-audit-details', 'جزئیات رویدادها', 'هر رویداد دارای Action, Target, Details, Timestamp است.'),
  c('owner', 'own-audit-200', 'نمایش ۲۰۰+ رویداد آخر', 'لاگ حوادث حداقل ۲۰۰ مورد آخر را در UI نشان میدهد.'),
  c('owner', 'owner-cannot-harm', 'محافظت از مالک در برابر خود', 'مالک نمیتواند خودش، رمز خود را از طریق مدیریت ادمین کم کند.'),
  c('owner', 'adm-session-invalidation', 'Invalidation کامل نشستها', 'ناسازگار شدن و پاکشدن همهٔ نشستهای ادمین در revoke/delete.'),
  c('owner', 'adm-unique-username', 'یوزرنیم یکتا', 'تکرارفناپذیری یوزرنیم ادمینها در Backend.'),
  // ------------------------------------------------------------------- UI
  c('ui', 'ui-fa', 'رابط کاملاً فارسی', 'لندینگ API و پیامهای خطا/پاسخ به فارسی و RTL هستند.'),
  c('ui', 'ui-rtl', 'چیدمان RTL', 'کل پنل راستبهچپ با dir=rtl.'),
  c('ui', 'ui-dark-light', 'Dark / Light Mode', 'تغییر پوستهٔ تاریک/روشن با ذخیرهٔ انتخاب.'),
  c('ui', 'ui-responsive', 'واکنشگرا', 'چیدمان تطبیقی موبایل و دسکتاپ.'),
  c('ui', 'ui-dashboard', 'داشبورد آمار', 'آمار رقمی از مسیر GET /api/stats (کاربران، نشستها، مصرف، ادمینها).'),
  c('ui', 'ui-sidebar', 'منوی کنار', 'لندینگ API-only جایگزین سایدبار کامل شده؛ ناوبری از مستندات API.'),
  c('ui', 'ui-users', 'صفحهٔ کاربران', 'مدیریت کاربران از API: /api/users و /api/user-create/update/delete.'),
  c('ui', 'ui-search', 'جستوجوی کاربران', 'جستو بر اساس نام، UUID و Token.'),
  c('ui', 'ui-config-page', 'صفحهٔ کانفیگ آهنین', 'ساخت کانفیگ EDGE PANEL از /api/config-build با چهار فرمت خروجی.'),
  c('ui', 'ui-scanner', 'صفحهٔ Scanner', 'Probe و Endpointها از /api/probe و /api/endpoints مدیریت میشوند.'),
  c('ui', 'ui-settings', 'صفحهٔ تنظیمات', 'تنظیمات brand/antiDetect/hostAliases/tlsPorts از /api/settings.'),
  c('ui', 'ui-install', 'صفحهٔ نصب', 'لندینگ شامل نمونه Login و Deploy و راهنمای secretهاست.'),
  c('ui', 'ui-admins', 'صفحهٔ مدیریت ادمین', 'مدیریت ادمینها فقط از API /api/admins/* با نقش و قدرت.'),
  c('ui', 'ui-audit', 'صفحهٔ Audit', 'لاگ حوادث از /api/audit با Actor/Action/Target قابل دریافت است.'),
  c('ui', 'ui-capabilities', 'صفحهٔ قابلیتها', 'مانیفست قابلیتها از /api/capabilities خوانده میشود.'),
  c('ui', 'ui-auto-modal', 'Modal ساخت ساب اتومات', 'ساخت ساب اتومات از /api/auto-build پس از Probe.'),
  c('ui', 'ui-user-modal', 'Modal ویرایش کاربر', 'ویرایش کاربر از /api/user-update با همهٔ فیلدها.'),
  c('ui', 'ui-toast', 'Toast موفقیت و خطا', 'اعلانهای موفقیت/خطای خودکار ناپدیدشونده.'),
  c('ui', 'ui-header', 'هدر اطلاعرسانی', 'لندینگ API نقش/قدرت نشست را در صورت ورود نشان میدهد.'),
  c('ui', 'ui-infinity', 'دکمههای ∞', 'کنار هر ورودی عددی (زمان، حجم، اتصال) که مقدار ۰ یعنی نامحدود.'),
  c('ui', 'ui-progress', 'Progress bar در ساخت', 'نوار پیشرفت برای ساخت ساب اتوماتیک.'),
  c('ui', 'ui-copy', 'دکمهٔ کپی', 'کپی لینکها و کانفیگها با کلیک.'),
  c('ui', 'ui-download', 'دانلود مستقیم فایل', 'دانلود خروجی کانفیگ بهعنوان فایل.'),
  c('ui', 'ui-error-safe', 'مدیریت خطا بدون کرش', 'خطاهای API به Toast تبدیل میشوند و رابط دستنخورده میماند.'),
  c('ui', 'ui-session-expire', 'ورود مجدد خودکار', 'در پایان Session فرم ورود خودکار نشان داده میشود.'),
  // ------------------------------------------------------------- settings
  c('settings', 'st-title', 'عنوان پنل', 'قابل تنظیم از تنظیمات.'),
  c('settings', 'st-brand', 'برند مالک', 'پیشفرض برند AMINCK GOD Edition در عنوانها و نام کانفیگها.'),
  c('settings', 'st-support', 'لینک پشتیبانی', 'محل نمایش در پنل و هدر ساببش.'),
  c('settings', 'st-doh', 'DoH اصلی', 'شروع اول برای رزولوشن و DNS.'),
  c('settings', 'st-doh-alt', 'DoHهای جایگزین', 'لیست جایگزین با failover.'),
  c('settings', 'st-health-url', 'Health URL', 'آدرس سلامت برای کانفیگهای خروجی.'),
  c('settings', 'st-template', 'قالب نام', 'قالب عمومی نام کانفیگ.'),
  c('settings', 'st-default-paths', 'تعداد پیشفرض مسیر', 'پیشفرض ساخت برای کاربران جدید.'),
  c('settings', 'st-update-interval', 'بازهٔ Update', 'فاصلهٔ بهروزرسانی ساببش به ساعت.'),
  c('settings', 'st-fingerprint', 'Fingerprint پیشفرض', 'برای کانفیگهای جدید.'),
  c('settings', 'st-profile', 'Profile Mode پیشفرض', 'Auto / Fallback / Load-Balance.'),
  c('settings', 'st-speed', 'Speed Preset پیشفرض', 'Stable / Balanced / Turbo / GOD (پیشفرض GOD با interval ۳۰، tolerance ۵۰ و retry ۲).'),
  c('settings', 'st-tls-ports', 'پورتهای TLS', 'فهرست پورتهای مجاز خروجی.'),
  c('settings', 'st-probe-results', 'نتایج Probe در تنضیمات', 'نمایش نتایج و آخرین زمان پرحب در تنظیمات/اسکنر.'),
  // -------------------------------------------------------------- deploy
  c('deploy', 'd-deploy-link', 'لینک Deploy به Cloudflare', 'لینک رسمی Deploy در README و صفحهٔ نصب.'),
  c('deploy', 'd-do-auto', 'Provision خودکار Durable Object', 'بدون هیچ D1/KV دستی؛ با migration خودکار ساخته میشود.'),
  c('deploy', 'd-cron-free', 'Deploy بدون سهمیه Cron', 'Auto-probe همراه ساخت ساب اجرا می‌شود تا پر بودن سهمیه Cron حساب مانع Deploy نشود.'),
  c('deploy', 'd-observability', 'Observability', 'فعالسازی در wrangler.jsonc.'),
  c('deploy', 'd-dev-vars', 'یک Secret در Deploy', 'Deploy رسمی فقط ADMIN_PASSWORD را از روی .dev.vars.example درخواست می‌کند.'),
  c('deploy', 'd-bindings-docs', 'مستندات Bindings در package.json', 'شرح Bindingها در توضیحات package.'),
  c('deploy', 'd-ci-template', 'قالب CI برای GitHub Actions', 'قالب آماده تست، type-check، audit و dry-run در docs/github-actions.'),
  c('deploy', 'd-deploy-template', 'قالب Deploy خودکار', 'قالب wrangler-action با Secretهای رمزگذاری‌شده در docs/github-actions.'),
  c('deploy', 'd-no-api-token', 'عدم دریافت API Token کلودفلر', 'هیچجای پنل Token کلودفلر دریافت/ذخیره نمیشود.'),
  c('deploy', 'd-healthz', 'Health عمومی', '/healthz برای مانیتورینگ بیرونی.'),
  // --------------------------------------------------------- edge panel extras
  c('config', 'cfg-edge-brand', 'برند AMINCK GOD Edition', 'همهٔ کانفیگها و سابها با برند EDGE PANEL نامگذاری میشوند.'),
  c('config', 'cfg-anti-padding', 'Path Padding', 'پدینگ تصادفی query روی path برای تنوع مسیر و کاهش برخورد مسیرها.'),
  c('config', 'cfg-anti-jitter', 'Path Jitter', 'طول slug مسیر بین ۶ تا ۱۲ کاراکتر متغیر است.'),
  c('config', 'cfg-anti-fragment', 'TLS Fragment', 'راهنمای fragment در VLESS/Clash/sing-box برای عبور از فیلتر.'),
  c('config', 'cfg-owned-aliases', 'Host Alias متعلق به مالک', 'چرخش Host فقط میان دامنه‌هایی که در Endpointهای همین Worker ثبت شده‌اند.'),
  c('config', 'cfg-multiport', 'انتخاب پورت Zooz/BPB', 'گسترش خروجی روی پورتهای TLS کلودفلر (443/2053/2083/2087/2096/8443).'),
  c('config', 'cfg-god-speed', 'پروفایل سرعت GOD', 'health interval ۳۰، tolerance ۵۰، دو retry سریع، earlyData ۴۰۹۶ و tcp-concurrent.'),
  c('config', 'cfg-iron-local', 'پک آهنین تجمیعی چندکلاینتی', 'هرکدام از یک تا پنج پروفایل Xray و sing-box همه مسیرهای ذخیره‌شده را با leastPing یا urltest تجمیع می‌کند.'),
  c('config', 'cfg-hot-update', 'آپدیت یککلیکی', 'POST /api/hot-update مسیرها را بدون قطعی دامنه بازسازی میکند.'),
  c('ui', 'ui-api-only', 'پنل ساده فروش ساب', 'ورود مرورگری + API JSON؛ ساخت مشترک و لینک ساب برای V2Box / V2Ray / MahsaNG / NapsternetV.'),
  c('security', 'sec-api-only-surface', 'سطح حمله کنترلشده', 'Same-Origin روی همهٔ mutating APIها؛ کوکی HttpOnly.'),
  c('config', 'cfg-iron-json', 'کانفیگ آهنین JSON', 'POST /api/iron-build بین ۱ تا ۵ پروفایل استاندارد Xray و sing-box را با تمام Routeهای ساب تا سقف ۲۰۰۰ می‌سازد.'),
  c('scanner', 'scan-clean-ips', 'مخزن کاندیدهای Anycast', 'GET /api/clean-ips فهرست کاندیدها و هشدار تست از ISP واقعی را برمی‌گرداند.'),
  c('config', 'cfg-aminck-brand-token', 'توکن AMINCK در نام کانفیگ', 'قالب پیشفرض نام شامل AMINCK است تا در همهٔ کلاینت‌ها دیده شود.'),
  c('config', 'cfg-aminck-multi', 'گروه مولتی‌پروکسی AMINCK-MULTI', 'Clash load-balance با consistent-hashing روی همهٔ مسیرها.'),
  c('config', 'cfg-aminck-yt', 'گروه AMINCK-YOUTUBE', 'url-test جدا برای دامنهٔ یوتیوب در خروجی Clash.'),
  c('config', 'cfg-aminck-ig', 'گروه AMINCK-INSTA', 'url-test جدا برای اینستاگرام در خروجی Clash.'),
  c('config', 'cfg-aminck-tt', 'گروه AMINCK-TIKTOK', 'url-test جدا برای تیک‌تاک در خروجی Clash.'),
  c('config', 'cfg-media-rules', 'قوانین دامنه رسانه', 'youtube/instagram/tiktok به گروه‌های اختصاصی AMINCK هدایت می‌شوند.'),
  c('config', 'cfg-god-fast-failover', 'Failover سریع GOD', 'health-check هر ۳۰ ثانیه و tolerance ۵۰ برای تعویض مسیر خراب بدون فشار بی‌مورد.'),
  c('config', 'cfg-god-retry2', 'دو تلاش سریع TCP در GOD', 'دو تلاش کوتاه به‌جای شش retry کند، برای کاهش زمان انتظار endpoint خراب.'),
  c('config', 'cfg-multiport-optin', 'مولتی‌پورت اختیاری', 'پیش‌فرض خاموش و 443 است؛ مالک Custom Domain می‌تواند پورت‌های سازگار را فعال کند.'),
  c('config', 'cfg-alias-validation', 'اعتبارسنجی Host Alias', 'Alias شخص ثالث رد می‌شود و Alias باید در Endpointهای همین Worker وجود داشته باشد.'),
  c('config', 'cfg-no-third-party-host', 'بدون Host شخص ثالث', 'خروجی خودکار هیچ نام تجاری یا دامنه شخص ثالث را جعل نمی‌کند.'),
  c('config', 'cfg-alias-empty-default', 'Alias پیش‌فرض خالی', 'نصب تازه فقط از hostname واقعی Worker استفاده می‌کند.'),
  c('config', 'cfg-legacy-alias-migration', 'پاکسازی Alias قدیمی', 'مهاجرت تنظیمات، دامنه‌های قدیمی را مگر آنکه Endpoint همین Worker باشند حذف می‌کند.'),
  c('config', 'cfg-name-edit', 'ویرایش قالب نام هر مشترک', 'user-update فیلد configNameTemplate را ذخیره می‌کند.'),
  c('traffic', 'tr-limit-requests', 'سقف درخواست ساب', 'limitRequests=0 نامحدود؛ در غیر این صورت fetch ساب ۴۲۹ می‌شود.'),
  c('traffic', 'tr-request-count', 'شمارش درخواست ساب', 'هر دریافت /sub شمارنده requestCount را زیاد می‌کند.'),
  c('traffic', 'tr-unlimited-requests', 'درخواست نامحدود', 'صفر در limitRequests هرگز به پیشفرض تبدیل نمی‌شود.'),
  c('ui', 'ui-unlimited-btn', 'دکمه نامحدود کنار محدودیت‌ها', 'حجم، زمان، اتصال و سقف درخواست با یک کلیک صفر می‌شوند.'),
  c('ui', 'ui-edit-user', 'فرم ویرایش کانفیگ/مشترک', 'نام، قالب، تعداد مسیر و محدودیت‌ها از پنل قابل ویرایش است.'),
  c('ui', 'ui-path-pick', 'انتخاب تعداد کانفیگ ساب', '۱ تا ۲۰۰۰ مسیر در ساخت اتومات مالک قابل انتخاب است و بالاتر از ۲۰۰ هشدار موبایل دارد.'),
  c('ui', 'ui-caps-tab', 'تب فهرست قابلیت‌ها', 'مانیفست از /api/capabilities در پنل خوانده می‌شود.'),
  c('ui', 'ui-easy-setup', 'لینک ستاپ یک‌کلیکی', 'منوی Deploy رسمی Cloudflare با تنظیمات wrangler ازپیش‌پر.'),
  c('ui', 'ui-no-token-form', 'بدون فرم دریافت توکن', 'پنل هیچ API Token کلودفلر را دریافت یا به Worker ارسال نمی‌کند.'),
  c('deploy', 'd-launch-api', 'API عمومی launch', 'GET /api/launch لینک مخزن، Dashboard و Deploy رسمی را بدون نشست برمی‌گرداند.'),
  c('sub', 'sub-auto-iron', 'آهنین همراه ساخت اتومات', 'auto-build می‌تواند ironCount ۱ تا ۵ را در همان پاسخ بدهد.'),
  c('sub', 'sub-count-select', 'تعداد مسیر در auto-build', 'paths در auto-build با سقف قدرت ادمین محدود می‌شود.'),
  c('config', 'cfg-200-in-one', 'پنجره پیشنهادی ۲۰۰ پروکسی موبایل', 'پنل ساخت تا ۲۰۰ مسیر در یک ساب را به‌عنوان پنجره پیشنهادی سازگار با موبایل نگه می‌دارد؛ حالت Giant بالاتر از آن Opt-in است.'),
  c('config', 'cfg-ws-alpn', 'ALPN سازگار WebSocket', 'خروجی VLESS/Clash/sing-box از http/1.1 سازگار با WebSocket Upgrade استفاده می‌کند.'),
  c('config', 'cfg-ws-ua', 'User-Agent استاندارد روی WS', 'هدر User-Agent سازگار برای کلاینت‌هایی که ws headers را پشتیبانی می‌کنند.'),
  c('config', 'cfg-fragment-optin', 'Fragment Hint اختیاری', 'به‌دلیل تفاوت کلاینت‌ها پیش‌فرض خاموش است و مالک می‌تواند بازه ۵۰–۱۲۰ را فعال کند.'),
  c('config', 'cfg-clean-front', 'فرانت Anycast اختیاری', 'Auto Build می‌تواند direct و کاندید Anycast را ترکیب کند؛ آدرس اتصال عوض می‌شود ولی SNI/Host همان Worker واقعی می‌ماند.'),
  c('config', 'cfg-aminck-tunnel', 'گروه AMINCK-TUNNEL', 'گروه fallback اختصاصی تانل در Clash.'),
  c('config', 'cfg-in-socks', 'اینباند SOCKS اختصاصی', 'Clash socks-port 10808 و sing-box tag aminck-in.'),
  c('config', 'cfg-in-http', 'اینباند HTTP اختصاصی', 'Clash port 10809 کنار mixed-port.'),
  c('scanner', 'scan-clean-18', 'هجده کاندید Anycast', 'مخزن حداقل ۱۸ کاندید دارد؛ فقط با گزینه کاربر اضافه می‌شوند و انتخاب واقعی به تست کلاینت سپرده می‌شود.'),
  c('sub', 'sub-batch-10', 'ساخت دسته‌ای تا ۱۰ ساب', 'Auto Build در یک درخواست ۱، ۲، ۳، ۵ یا ۱۰ مشترک مستقل با Token و UUID جدا می‌سازد.'),
  c('ui', 'ui-batch-picker', 'انتخاب تعداد ساب', 'داشبورد تعداد ساب مستقل را جدا از تعداد کانفیگ داخل هر ساب می‌گیرد.'),
  c('owner', 'own-portable-restore', 'Restore قابل حمل', 'مالک بکاپ JSON را روی Deploy جدید بازیابی می‌کند و Token و UUID مشترک‌ها حفظ می‌شود.'),
  c('owner', 'own-route-rebind', 'اتصال بکاپ به دامنه جدید', 'Restore همه مسیرهای معتبر را به hostname همین Deploy متصل می‌کند.'),
  c('deploy', 'd-one-secret', 'Deploy با یک Secret', 'Wizard رسمی فقط ADMIN_PASSWORD را می‌پرسد؛ Sessionها Token تصادفی server-side هستند.'),
  c('ui', 'ui-recovery-tab', 'تب بکاپ و بازیابی', 'دانلود Backup و Restore فایل از رابط فارسی بدون CLI انجام می‌شود.'),
  c('sub', 'sub-cold-start-safe', 'ساب پایدار پس از Cold Start', 'کاربرها از Map واقعی Durable Object Storage بازخوانی می‌شوند تا Token و مسیر بعد از Restart به ۴۰۴ تبدیل نشود.'),
  c('scanner', 'scan-backend-auto-build', 'Probe اجباری در Backend', 'خود API ساخت اتومات قبل از انتخاب Endpoint تست Edge را اجرا می‌کند و فقط موارد سالم را ترجیح می‌دهد.'),
  c('ui', 'ui-raw-test-link', 'نمایش و تست VLESS خام', 'کنار هر ساب لینک Raw قابل مشاهده و دکمه کپی مستقل وجود دارد.'),
  c('config', 'build-endpoint-select', 'انتخاب دامنه‌های واقعی', 'Auto Build انتخاب چند Endpoint یا انتخاب همه را می‌پذیرد و فقط همان گزینه‌ها را Probe می‌کند.'),
  c('config', 'build-route-count-free', 'تعداد آزاد ۱ تا ۲۰۰۰', 'تعداد کانفیگ به‌جای فهرست ثابت با ورودی عددی و سقف قدرت Backend انتخاب می‌شود.'),
  c('scanner', 'scan-owned-marker', 'تأیید مالکیت مسیر Worker', 'Probe فقط پاسخ سالم /healthz با Marker خود AMINNOVA را معتبر می‌داند و دامنه نامرتبط را وارد خروجی نمی‌کند.'),
  c('scanner', 'scan-browser-ws', 'تست کامل تونل از ISP مرورگر', 'بعد از ساخت، پنل از شبکه همان کاربر WSS را باز می‌کند، هدر VLESS و درخواست TCP واقعی می‌فرستد و فقط دریافت پاسخ باینری معتبر را موفق می‌داند.'),
  c('config', 'cfg-workers-ai-advice', 'راهنمای اختیاری Workers AI', 'با انتخاب کاربر، binding رسمی Cloudflare فقط از اعداد Probe یک Profile معتبر پیشنهاد می‌دهد؛ Timeout یا سهمیه هرگز ساخت را متوقف نمی‌کند.'),
  // ---------------------------------------------------- liquid/PWA/rolling pool
  c('deploy', 'pwa-web-manifest', 'Web App Manifest نصب‌پذیر', 'manifest.webmanifest نام، رنگ، حالت standalone، آیکون و Scope اپ AMINNOVA را تعریف می‌کند.'),
  c('deploy', 'pwa-service-worker', 'Service Worker اختصاصی', 'Service Worker پوسته عمومی پنل را برای اجرای نصب‌شده و بازیابی سریع فایل‌های رابط مدیریت می‌کند.'),
  c('security', 'pwa-no-api-cache', 'عدم Cache API در PWA', 'Service Worker همه مسیرهای /api را از Cache کنار می‌گذارد تا پاسخ مدیریتی حساس ذخیره نشود.'),
  c('security', 'pwa-no-sub-cache', 'عدم Cache Subscription در PWA', 'Service Worker مسیرهای خصوصی /sub را هرگز Cache نمی‌کند و Token داخل Cache مرورگر قرار نمی‌گیرد.'),
  c('security', 'pwa-no-ws-cache', 'عدم Cache مسیر WebSocket', 'Service Worker مسیرهای اتصال /e را مدیریت یا Cache نمی‌کند و Upgrade مستقیماً به Worker می‌رسد.'),
  c('deploy', 'pwa-offline-shell', 'پوسته آفلاین پنل', 'در نبود شبکه فقط پوسته عمومی از Cache باز می‌شود و عملیات حساس همچنان به Backend آنلاین نیاز دارد.'),
  c('deploy', 'pwa-cache-version', 'نسخه‌بندی Cache اپ', 'نام Cache نسخه‌دار است و Activate نسخه‌های قدیمی پوسته را به‌صورت خودکار حذف می‌کند.'),
  c('deploy', 'pwa-skip-waiting', 'فعال‌سازی نسخه جدید PWA', 'پیام SKIP_WAITING نسخه نصب‌شده جدید را بدون باقی‌ماندن طولانی Worker قدیمی فعال می‌کند.'),
  c('deploy', 'pwa-app-scope', 'Scope کامل اپ نصب‌شده', 'Service-Worker-Allowed و manifest scope روی ریشه تنظیم شده تا همه تب‌های پنل داخل اپ کار کنند.'),
  c('ui', 'pwa-install-button', 'دکمه نصب اپ', 'رویداد beforeinstallprompt ذخیره و دکمه نصب در Login، Topbar و تب موبایل نمایش داده می‌شود.'),
  c('ui', 'pwa-installed-state', 'تشخیص حالت نصب‌شده', 'display-mode standalone و navigator.standalone تشخیص می‌دهند که پنل هم‌اکنون به‌شکل اپ اجرا شده است.'),
  c('ui', 'pwa-update-check', 'بررسی دستی آپدیت اپ', 'تب اپ موبایل با registration.update نسخه جدید فایل‌های نصب‌شده را از Worker بررسی می‌کند.'),
  c('ui', 'pwa-online-indicator', 'نشانگر آنلاین و آفلاین', 'رویدادهای online و offline وضعیت زنده شبکه را در نوار شیشه‌ای پنل به‌روزرسانی می‌کنند.'),
  c('ui', 'pwa-mobile-shortcuts', 'Shortcutهای اپ نصب‌شده', 'Manifest میانبر مستقیم برای ساخت ساب و مدیریت مشترک‌ها روی دستگاه ارائه می‌دهد.'),
  c('ui', 'pwa-native-share', 'اشتراک‌گذاری بومی موبایل', 'Web Share API لینک خصوصی انتخاب‌شده را با Share Sheet سیستم‌عامل ارسال می‌کند و Copy جایگزین دارد.'),
  c('ui', 'pwa-format-copy', 'کپی فرمت در اپ همراه', 'اپ همراه لینک‌های Base64، Raw، Clash و sing-box هر مشترک را جداگانه کپی می‌کند.'),
  c('ui', 'pwa-rotation-monitor', 'مانیتور Rotation داخل اپ', 'مانیتور اختیاری هنگام باز بودن اپ هر دقیقه هدرهای Pool ساب انتخابی را دریافت و نمایش می‌دهد.'),
  c('ui', 'pwa-monitor-stop', 'توقف خودکار مانیتور', 'با خروج از تب اپ، Interval مانیتور پاک می‌شود تا درخواست پس‌زمینه ناخواسته ادامه نداشته باشد.'),
  c('ui', 'pwa-mobile-bottom-nav', 'ناوبری پایین موبایل', 'در نمایشگر کوچک همه بخش‌ها با Bottom Navigation شیشه‌ای، افقی و مناسب لمس در دسترس هستند.'),
  c('ui', 'pwa-safe-area', 'پشتیبانی Safe Area موبایل', 'ناوبری نصب‌شده از env safe-area-inset-bottom برای فاصله مناسب با نوار Home استفاده می‌کند.'),
  c('sub', 'pool-unlimited-time', 'Smart Pool نامحدود زمانی', 'یک Subscription می‌تواند در Refreshهای متوالی نسل‌های نامحدود پنجره فعال تولید کند بدون پاسخ نامتناهی.'),
  c('sub', 'pool-bounded-window', 'پنجره فعال با سقف مشخص', 'هر پاسخ حداکثر ۲۰۰۰ مسیر دارد؛ UI برای Client-safe بودن ۲۰۰ یا کمتر را پیشنهاد و درباره Giant هشدار می‌دهد.'),
  c('sub', 'pool-minute-cadence', 'چرخش یک‌دقیقه‌ای Pool', 'rotationMinutes از ۱ تا ۶۰ قابل تنظیم است و پیش‌فرض Smart Pool روی یک دقیقه قرار دارد.'),
  c('sub', 'pool-deterministic-epoch', 'Epoch تعیین‌پذیر چرخش', 'شماره دوره از زمان و بازه Rotation محاسبه می‌شود تا همه خروجی‌های همان دقیقه سازگار بمانند.'),
  c('sub', 'pool-next-rotation', 'زمان Rotation بعدی', 'Backend زمان دقیق دوره بعدی را محاسبه و در پاسخ داخلی و هدر Subscription اعلام می‌کند.'),
  c('sub', 'pool-route-order', 'چرخش ترتیب مسیرها', 'در هر Epoch ترتیب مسیرهای معتبر جابه‌جا می‌شود تا اولویت ثابت روی یک مسیر باقی نماند.'),
  c('sub', 'pool-anycast-assignment', 'چرخش آدرس Anycast', 'کاندیدهای معتبر Cloudflare در هر Epoch دوباره میان مسیرهای فعال توزیع می‌شوند.'),
  c('sub', 'pool-direct-anchor', 'لنگر Direct در Pool', 'مسیر اول و هر دهمین مسیر Direct باقی می‌ماند تا کاندید نامناسب کل پنجره را از دسترس خارج نکند.'),
  c('sub', 'pool-stable-paths', 'Path پایدار هنگام Rotation', 'چرخش فقط اولویت و آدرس اتصال را تغییر می‌دهد و Pathهای مجاز را نمی‌شکند.'),
  c('sub', 'pool-stable-token', 'Token پایدار هنگام Rotation', 'Token Subscription در چرخش خودکار ثابت می‌ماند تا لینک نصب‌شده کلاینت باطل نشود.'),
  c('sub', 'pool-stable-uuid', 'UUID پایدار هنگام Rotation', 'UUID VLESS هنگام تغییر پنجره ثابت است و اتصال‌های جاری عمداً قطع نمی‌شوند.'),
  c('sub', 'pool-mode-header', 'هدر وضعیت Pool', 'x-aminck-pool-mode حالت fixed یا rolling را برای عیب‌یابی کلاینت اعلام می‌کند.'),
  c('sub', 'pool-epoch-header', 'هدر Epoch فعال', 'x-aminck-rotation-epoch نسل فعلی خروجی چرخان را در پاسخ ساب مشخص می‌کند.'),
  c('sub', 'pool-refresh-header', 'هدر پیشنهاد Refresh', 'x-aminck-refresh-seconds بازه پیشنهادی Refresh را بر حسب ثانیه به ابزارهای سازگار می‌دهد.'),
  c('sub', 'pool-route-count-header', 'هدر تعداد مسیر فعال', 'x-aminck-active-routes اندازه پنجره فعلی را بدون نیاز به Parse کامل payload نمایش می‌دهد.'),
  c('sub', 'pool-private-no-store', 'No-store اجباری ساب چرخان', 'پاسخ Subscription با private، no-store و must-revalidate مانع نگهداری نسخه حساس در Cache واسط می‌شود.'),
  c('sub', 'pool-etag-generation', 'ETag نسل Subscription', 'ETag ضعیف از شناسه غیرمحرمانه کاربر، configGeneration، Epoch و فرمت برای تشخیص نسل ساخته می‌شود.'),
  c('config', 'pool-all-formats', 'Rotation در همه فرمت‌ها', 'پنجره چرخان پیش از ساخت Base64، Raw، Clash، sing-box و Iron به BuildContext اعمال می‌شود.'),
  c('owner', 'pool-user-toggle', 'فعال‌سازی Pool برای هر مشترک', 'فرم ویرایش مشترک dynamicPool را مستقل از سایر کاربران روشن یا خاموش می‌کند.'),
  c('owner', 'pool-user-cadence', 'بازه مستقل هر مشترک', 'rotationMinutes در رکورد هر مشترک ذخیره و در فرم مدیریت بین ۱ تا ۶۰ دقیقه تنظیم می‌شود.'),
  c('owner', 'pool-backup-fields', 'بکاپ تنظیمات Pool', 'dynamicPool، rotationMinutes و فهرست Anycast معتبر همراه بکاپ مشترک نگهداری می‌شوند.'),
  c('security', 'pool-restore-validation', 'اعتبارسنجی Pool در Restore', 'Restore فقط IPهای داخل بازه رسمی Cloudflare و بازه Rotation معتبر را از بکاپ می‌پذیرد.'),
  c('security', 'pool-coldstart-normalize', 'نرمال‌سازی Pool بعد Cold Start', 'رکوردهای قدیمی یا ناقص هنگام بارگذاری Durable Object با مقادیر امن Pool نرمال می‌شوند.'),
  c('ui', 'ui-liquid-glass', 'طراحی Liquid Glass', 'کارت‌ها، Topbar، Navigation و لایه‌های اصلی از شفافیت، Blur و Border شیشه‌ای واکنش‌گرا استفاده می‌کنند.'),
  c('ui', 'ui-liquid-orbs', 'نورهای متحرک پس‌زمینه', 'دو Orb گرادیانی با Animation آرام عمق بصری ایجاد می‌کنند و Pointer Event ندارند.'),
  c('ui', 'ui-card-rise', 'ورود انیمیشنی کارت‌ها', 'کارت‌ها و آمار با انیمیشن کوتاه rise ظاهر می‌شوند تا جابه‌جایی صفحه قابل درک باشد.'),
  c('ui', 'ui-logo-pulse', 'لوگوی متحرک کنترل‌شده', 'لوگوی AMINNOVA با حرکت آهسته و سایه رنگی بدون وابستگی به تصویر خارجی نمایش داده می‌شود.'),
  c('ui', 'ui-button-shine', 'بازتاب متحرک دکمه', 'Hover دکمه‌ها یک نوار بازتاب کوتاه و Transform سبک دارد و ساختار صفحه را جابه‌جا نمی‌کند.'),
  c('ui', 'ui-reduced-motion', 'احترام به Reduced Motion', 'Media Query مربوط به prefers-reduced-motion همه Animationهای غیرضروری را برای دسترس‌پذیری متوقف می‌کند.'),
  c('ui', 'ui-inline-svg-icons', 'آیکون‌های SVG داخلی', 'ناوبری و اکشن‌ها از آیکون SVG خطی داخلی استفاده می‌کنند و به CDN یا فونت آیکون وابسته نیستند.'),
  c('ui', 'ui-sticky-glass-topbar', 'Topbar شیشه‌ای چسبان', 'نوار وضعیت و اکشن‌های اصلی هنگام Scroll با Blur و Safe Border در بالای صفحه می‌مانند.'),
  c('ui', 'ui-sticky-desktop-tabs', 'تب‌های چسبان دسکتاپ', 'ناوبری دسکتاپ زیر Topbar ثابت می‌ماند و تب فعال با گرادیان مشخص می‌شود.'),
  c('ui', 'ui-responsive-feature-grid', 'Feature Grid واکنش‌گرا', 'کارت‌های معرفی از سه ستون به دو و یک ستون با عرض دستگاه تبدیل می‌شوند.'),
  c('ui', 'ui-focus-rings', 'Focus Ring واضح', 'Input، Select و Textarea در Focus حاشیه Cyan و Ring قابل مشاهده برای کار با کیبورد دارند.'),
  c('ui', 'ui-heavy-preset', 'Preset یک‌کلیکی MAX Heavy', 'دکمه MAX Heavy تعداد فعال را ۲۰۰، Iron را ۵، Pool را روشن و Rotation را یک دقیقه می‌کند.'),
  c('ui', 'ui-domain-select-all', 'انتخاب همه دامنه‌ها', 'دکمه انتخاب همه تمام Endpointهای نمایش‌داده‌شده را برای Auto Build فعال می‌کند.'),
  c('ui', 'ui-domain-select-none', 'لغو انتخاب دامنه‌ها', 'دکمه لغو همه امکان ساخت انتخاب دقیق Endpointها را بدون کلیک تکی فراهم می‌کند.'),
  c('ui', 'ui-capability-search', 'جست‌وجوی زنده قابلیت‌ها', 'تب قابلیت‌ها عنوان و توضیح مانیفست را هم‌زمان با تایپ کاربر فیلتر می‌کند.'),
  c('ui', 'ui-capability-category', 'فیلتر دسته قابلیت‌ها', 'فهرست مانیفست با Select دسته‌های protocol، security، config، PWA و سایر بخش‌ها محدود می‌شود.'),
  c('ui', 'ui-capability-counter', 'شمارنده نتیجه قابلیت‌ها', 'پس از هر Search یا تغییر دسته تعداد موارد قابل مشاهده فوراً محاسبه و نمایش داده می‌شود.'),
  c('ui', 'ui-url-tab-state', 'حفظ تب در URL', 'پارامتر tab در History به‌روزرسانی می‌شود و بازکردن لینک داخلی بخش انتخابی را بازیابی می‌کند.'),
  c('ui', 'ui-academy-guide', 'راهنمای مرحله‌ای Academy', 'تب راهنما مراحل Deploy، ورود، ساخت، Import، Refresh، Smart Pool، پایداری و اپ موبایل را توضیح می‌دهد.'),
  c('ui', 'ui-honest-vpn-limit', 'توضیح محدودیت VPN مرورگر', 'اپ همراه شفاف اعلام می‌کند PWA مجوز VpnService ندارد و اتصال واقعی باید با کلاینت استاندارد انجام شود.'),
  c('ui', 'ui-ws-result-color', 'وضعیت رنگی تست WSS', 'نتیجه تست مرورگر با Border سبز یا قرمز و پیام قابل اقدام بعد از ساخت نمایش داده می‌شود.'),
  c('ui', 'ui-smart-pool-badge', 'Badge Pool در مشترک‌ها', 'کاربر چرخان در جدول مدیریت با نشان ∞ و دقیقه Rotation از کاربر ثابت قابل تشخیص است.'),
  c('ui', 'ui-max-active-copy', 'توضیح سقف فعال Heavy', 'رابط تفاوت پنجره ۲۰۰ مسیره Client-safe و نسل‌های نامحدود زمانی را پیش از ساخت توضیح می‌دهد.'),
  c('deploy', 'pwa-local-icon', 'آیکون محلی Maskable', 'icon.svg داخل همان Worker ارائه می‌شود و Manifest آن را برای حالت any و maskable ثبت می‌کند.'),
  c('deploy', 'pwa-theme-meta', 'رنگ پوسته سیستم‌عامل', 'theme-color و color-scheme نوار مرورگر و پنجره اپ نصب‌شده را با Liquid Glass هماهنگ می‌کنند.'),
  c('deploy', 'pwa-apple-meta', 'متادیتای نصب iOS', 'apple-mobile-web-app-capable، عنوان و Status Bar برای افزودن پنل به Home Screen ثبت شده‌اند.'),
  c('security', 'pwa-same-origin-assets', 'دارایی‌های PWA هم‌مبدأ', 'Manifest، Service Worker، CSS، JavaScript و Icon فقط از همان Worker و زیر هدرهای امنیتی ارائه می‌شوند.'),
  c('security', 'sub-pragma-no-cache', 'Pragma امن Subscription', 'علاوه بر Cache-Control، هدر pragma no-cache برای واسط‌های قدیمی روی ساب تنظیم می‌شود.'),
  c('config', 'cfg-nonloop-health', 'Health Check بدون TCP Loop', 'URLTest پیش‌فرض به مقصد عمومی مستقل می‌رود و هرگز Worker را از داخل تونل خودش صدا نمی‌زند؛ این کار Timeout کاذب همه مسیرها را حذف می‌کند.'),
  c('config', 'cfg-direct-safe-anchor', 'مسیر DIRECT SAFE سازگار', 'تمام مسیرهای مستقیم بدون Anycast، Fragment، Path padding و Early Data صادر می‌شوند تا کلاینت یا Middlebox ناسازگار مسیر محافظه‌کار داشته باشد.'),
  c('protocol', 'proto-ws-pair-direction', 'جهت صحیح WebSocketPair', 'سمت Client از Pair به پاسخ 101 برگردانده و سمت Server داخل Worker accept می‌شود تا Frameهای VLESS واقعاً به Handler برسند.'),
  c('protocol', 'proto-connect-deadline', 'Deadline واقعی اتصال TCP', 'بازشدن Socket و مرحله Connect هر دو Deadline دارند؛ مقصد خراب دیگر WebSocket را بی‌نهایت باز و معطل نگه نمی‌دارد.'),
  c('protocol', 'proto-fast-doh-race', 'Failover هم‌زمان DoH', 'Resolverهای مجاز هم‌زمان پرسیده می‌شوند تا خرابی Resolver اول چند Timeout متوالی پیش از اتصال ایجاد نکند.'),
  c('scanner', 'scan-vless-payload', 'Probe با Payload واقعی VLESS', 'تست مرورگر بعد از 101 یک Packet استاندارد VLESS و درخواست HTTP می‌فرستد و صرف بازشدن WebSocket را موفق گزارش نمی‌کند.'),
  c('deploy', 'deploy-release-marker', 'شناسه Release قابل بررسی', 'healthz، Subscription و Topbar شناسه نسخه Timeout Fix را نمایش می‌دهند تا Deploy قدیمی فوراً تشخیص داده شود.'),
  c('protocol', 'proto-native-dns-fallback', 'Fallback امن DNS داخلی Worker', 'اگر همه DoHهای مجاز موقتاً قطع باشند، پس از رد نام‌های محلی و خاص، DNS داخلی Workers Sockets اجازه نمی‌دهد کل اینترنت با dns-unresolvable از کار بیفتد.'),
  c('protocol', 'proto-dns-short-cache', 'Cache کوتاه DNS عمومی', 'پاسخ عمومی DoH برای شصت ثانیه در Isolate نگهداری می‌شود تا اتصال‌های متوالی موبایل هر بار هزینه Resolve و Timeout ندهند.'),
  c('config', 'cfg-current-host-priority', 'اولویت دامنه فعال پنل', 'دامنه‌ای که درخواست ساخت را به همین Worker رسانده همیشه در انتخاب مجاز Route اول است تا Endpoint قدیمی یا حذف‌شده کانفیگ اصلی نشود.'),
  c('config', 'cfg-rescue-rebind', 'تعمیر یک‌کلیکی همه ساب‌ها', 'دکمه نجات Token و UUID را حفظ می‌کند اما Route همه مشترک‌ها را با Stable و DIRECT SAFE به دامنه فعال فعلی متصل می‌کند.'),
  c('ui', 'ui-mobile-action-sheet', 'منوی پایین موبایل با Action Sheet', 'چهار بخش اصلی در نوار پایین پنج‌ستونه و ابزارهای تکمیلی در Sheet شیشه‌ای لمسی قرار می‌گیرند تا ناوبری موبایل فشرده و خوانا باشد.'),
  c('ui', 'ui-mobile-touch-layout', 'فرم لمسی تک‌ستونه', 'در موبایل فیلدها حداقل ارتفاع لمسی، فونت بدون Zoom ناخواسته iOS، Grid تک‌ستونه، آمار دو ستونه و Safe Area واقعی دارند.'),
  c('config', 'cfg-2000-owner-routes', 'تا ۲۰۰۰ کانفیگ در یک ساب', 'مالک Ultra می‌تواند به‌صورت Opt-in تا ۲۰۰۰ Route یکتا بسازد؛ پنل برای جلوگیری از کندی کلاینت بالای ۲۰۰ هشدار صریح نشان می‌دهد.'),
  c('config', 'cfg-iron-whole-sub', 'حالت آهنین برای کل Subscription', 'Iron Mode تمام Routeهای Subscription را با برچسب IRON و گروه‌های انتخاب خودکار خروجی می‌دهد؛ تعداد Route مستقل از تعداد بسته‌های JSON آهنین است.'),
  c('config', 'cfg-gaming-domain-rules', 'قواعد Gaming مبتنی بر دامنه رسمی', 'انتخاب بازی‌ها دامنه‌های رسمی Login، Launcher، Store و Content ناشر را در Clash، sing-box و Xray به گروه اندازه‌گیری‌شده هدایت می‌کند.'),
  c('deploy', 'deploy-github-version-check', 'بررسی نسخه GitHub از داخل پنل', 'Update Center نسخه Deploy جاری را با package.json شاخه عمومی مقایسه و در صورت وجود نسخه جدید لینک Deploy امن نشان می‌دهد.'),
  c('security', 'deploy-no-panel-cloudflare-token', 'آپدیت بدون دریافت توکن در پنل', 'پنل هرگز Cloudflare API Token نمی‌گیرد؛ نصب کد از Deploy رسمی یا Git Integration انجام می‌شود تا Secret مدیریتی وارد UI عمومی نشود.'),
  c('scanner', 'scan-operator-location-labels', 'برچسب مکان برای Deploy واقعی', 'مالک می‌تواند برای Endpointهای واقعاً مستقرشده برچسب مکان ثبت کند؛ پنل آن را در نام و انتخاب مسیر نمایش می‌دهد اما از Cloudflare Anycast کشور یا خروجی جعلی استنتاج نمی‌کند.'),
  c('config', 'cfg-low-ping-preset', 'پروفایل LOW PING', 'Preset کم‌تأخیر با Probe timeout کوتاه‌تر، یک تلاش سریع، Health interval پانزده‌ثانیه‌ای و tolerance بیست میلی‌ثانیه مسیر اندازه‌گیری‌شده را سریع‌تر انتخاب می‌کند.'),
  c('config', 'cfg-god-latency-tuning', 'تنظیم دوباره GOD برای قدرت', 'GOD با Health interval بیست‌وپنج ثانیه، tolerance سی‌وپنج میلی‌ثانیه، DNS failover و TCP concurrent تعادل قدرت و تشخیص خرابی سریع‌تری دارد.'),
  c('traffic', 'traffic-domestic-clash-direct', 'تداوم داخلی Clash', 'Domestic Direct قواعد DOMAIN-SUFFIX برای .ir و GEOIP ایران را پیش از قواعد تونل به DIRECT می‌فرستد تا Split Tunnel کلاینت به Worker وابسته نباشد.'),
  c('traffic', 'traffic-domestic-singbox-direct', 'تداوم داخلی sing-box', 'در sing-box دامنه‌های .ir هنگام فعال بودن Domestic Direct از Outbound مستقیم استفاده می‌کنند و ترافیک بین‌المللی همچنان به گروه اندازه‌گیری‌شده می‌رود.'),
  c('traffic', 'traffic-domestic-xray-direct', 'تداوم داخلی Xray', 'بسته Xray Iron برای geosite:ir و geoip:ir قانون direct صادر می‌کند؛ این قابلیت به دیتابیس GeoSite/GeoIP کلاینت وابسته است.'),
  c('config', 'cfg-ai-natural-language-plan', 'طراح کانفیگ با متن فارسی', 'POST /api/ai-plan نیاز فارسی کاربر را به یک طرح محدودشده شامل تعداد، بازی، Iron، LOW PING، Domestic Direct و نوع Failover تبدیل می‌کند.'),
  c('config', 'cfg-ai-deterministic-fallback', 'Fallback داخلی دستیار AI', 'اگر Binding، مدل، سهمیه یا پاسخ Cloudflare AI در دسترس نباشد، Parser امن فارسی بدون توقف فرم ساخت را با فیلدهای معتبر آماده می‌کند.'),
  c('ui', 'ui-ai-plan-and-build', 'طراحی و ساخت یک‌کلیکی AI', 'کاربر می‌تواند طرح AI را فقط بررسی کند یا با دکمه طراحی و ساخت، فیلدهای اعتبارسنجی‌شده را روی Auto Build اعمال و ساب را ایجاد کند.'),
  c('security', 'security-ai-plan-constraints', 'محدودسازی خروجی AI', 'دستیار فقط برای نشست دارای configs:build اجرا می‌شود، Prompt را محدود می‌کند و خروجی مدل را به Enumها، سقف Route و Game IDهای Catalogue تقلیل می‌دهد.'),
  ...GAME_CATALOG.map((game) => c(
    'config',
    `game-route-${game.id}`,
    `Gaming · ${game.title}`,
    `Preset قابل انتخاب ${game.title}، دامنه‌های رسمی Login/Launcher/Content ناشر ${game.publisher} را به گروه Gaming پروفایل هدایت می‌کند؛ UDP و Ping فیزیکی تضمین نمی‌شود.`,
  )),
];

export function totalCapabilities(): number {
  return CAPABILITIES.length;
}

/** Count of capabilities covering owner/administrator management. */
export function ownerCapabilitiesCount(): number {
  return CAPABILITIES.filter((x) => x.category === 'owner').length;
}

export function capabilitiesByCategory(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const cap of CAPABILITIES) out[cap.category] = (out[cap.category] ?? 0) + 1;
  return out;
}
